"""Default configuration values for strobengine execution."""

DEFAULT_CONCURRENCY: int = 10
DEFAULT_DURATION_SECS: int = 10
DEFAULT_TIMEOUT_SECS: int = 10
DEFAULT_START_CONCURRENCY: int = 10
DEFAULT_MAX_CONCURRENCY: int = 200
DEFAULT_RAMP_SECS: int = 60
DEFAULT_HOLD_SECS: int = 30
DEFAULT_BASELINE: int = 5
DEFAULT_PEAK_CONCURRENCY: int = 500
DEFAULT_PRE_SPIKE_SECS: int = 5
DEFAULT_SPIKE_SECS: int = 10
DEFAULT_POST_SPIKE_SECS: int = 5

# Keep in sync with MAX_CONCURRENCY in src/config.rs.
MAX_CONCURRENCY: int = 10_000
